### PR TITLE
Oops, get sdhand's username instead of nick

### PR DESCRIPTION
**Pull request by danieljabailey**

### CODE REVIEW

**Comment by LordAro** [comment]
Might as well remove a couple of the older people as well? (jalada & Din)

**Comment by danieljabailey** [comment]
LordAro: Remove them in another PR though?

**Comment by LordAro** [comment]
¯\\\_(ツ)_/¯ reduces merge commit spam

**Comment by danieljabailey** [comment]
Do you want me to add that change here then?

**Comment by barrucadu** [comment]
"Merge commit spam"

Merges within a branch are unhelpful noises. Merges of branches into master are fine.

**Pull request merged**
